# Generated by Django 3.2.16 on 2025-05-27 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='page_icons/', verbose_name='Иконка')),
                ('parent_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpages', to='workspaces.page', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='space_icons/', verbose_name='Иконка')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='space_banners/', verbose_name='Баннер')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Теги')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=20, verbose_name='Статус')),
                ('is_guest', models.BooleanField(default=False, verbose_name='Гостевое пространство')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('link', 'Link')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textelement_elements', to='workspaces.page', verbose_name='Страница')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textelement_elements', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Текстовое поле',
                'verbose_name_plural': 'Текстовые поля',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workspaces.workspace', verbose_name='Пространство'),
        ),
        migrations.CreateModel(
            name='LinkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('link', 'Link')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('linked_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_elements', to='workspaces.page', verbose_name='Связанная страница')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkelement_elements', to='workspaces.page', verbose_name='Страница')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkelement_elements', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Ссылка на страницу',
                'verbose_name_plural': 'Ссылки на страницы',
            },
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('link', 'Link')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(upload_to='element_images/', verbose_name='Изображение')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageelement_elements', to='workspaces.page', verbose_name='Страница')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageelement_elements', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='FileElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('link', 'Link')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='element_files/', verbose_name='Файл')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileelement_elements', to='workspaces.page', verbose_name='Страница')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fileelement_elements', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='CheckboxElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('checkbox', 'Checkbox'), ('text', 'Text'), ('link', 'Link')], default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkboxelement_elements', to='workspaces.page', verbose_name='Страница')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkboxelement_elements', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Чекбокс',
                'verbose_name_plural': 'Чекбоксы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('space', 'title')},
        ),
    ]
