# Generated by Django 3.2.16 on 2025-04-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('image', 'Изображение'), ('file', 'Файл'), ('checkbox', 'Чекбокс'), ('text', 'Текстовое поле'), ('link', 'Ссылка на страницу')], max_length=20, verbose_name='Тип элемента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='space_icons/', verbose_name='Иконка')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='space_banners/', verbose_name='Баннер')),
                ('tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Теги')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='not_started', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пространство',
                'verbose_name_plural': 'Пространства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textelement', to='workspaces.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Текстовое поле',
                'verbose_name_plural': 'Текстовые поля',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('link', models.SlugField(unique=True, verbose_name='Ссылка')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная страница')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workspaces.workspace', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkelement', to='workspaces.element', verbose_name='Элемент')),
                ('linked_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_elements', to='workspaces.page', verbose_name='Связанная страница')),
            ],
            options={
                'verbose_name': 'Ссылка на страницу',
                'verbose_name_plural': 'Ссылки на страницы',
            },
        ),
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='element_images/', verbose_name='Изображение')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imageelement', to='workspaces.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='FileElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='element_files/', verbose_name='Файл')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fileelement', to='workspaces.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.AddField(
            model_name='element',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='workspaces.page', verbose_name='Страница'),
        ),
        migrations.CreateModel(
            name='CheckboxElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Отмечено')),
                ('element', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkboxelement', to='workspaces.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'Чекбокс',
                'verbose_name_plural': 'Чекбоксы',
            },
        ),
    ]
