# Generated by Django 3.2.16 on 2025-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='page_icons/', verbose_name='Иконка'),
        ),
    ]
