# Generated by Django 3.2.16 on 2025-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.SlugField(verbose_name='Ссылка'),
        ),
    ]
